/**
 * Word lists ported faithfully from research-agora/scripts/writing_verify.py.
 * Keep these in sync with the Python source — they are the canonical lexicon.
 */

/** Filler words (single tokens), matched on word boundaries, case-insensitive. */
export const FILLER_WORDS: readonly string[] = [
  "basically",
  "simply",
  "just",
  "actually",
  "really",
  "very",
  "quite",
  "rather",
  "somewhat",
  "perhaps",
  "fairly",
  "literally",
  "essentially",
  "obviously",
  "clearly",
  "certainly",
  "definitely",
  "practically",
];

/** Multi-word filler phrases, matched as substrings (longest first to avoid nesting). */
export const FILLER_PHRASES: readonly string[] = [
  "in order to",
  "it should be noted that",
  "it is important to note that",
  "it is worth noting that",
  "as a matter of fact",
  "it goes without saying",
  "needless to say",
  "at the end of the day",
  "for all intents and purposes",
  "in the final analysis",
  "it can be seen that",
  "as we all know",
  "it is well known that",
  "it is interesting to note that",
];

/** Hedge words — these soften conviction (the engine reports density; the coach judges). */
export const HEDGE_WORDS: readonly string[] = [
  "might",
  "may",
  "could",
  "possibly",
  "potentially",
  "perhaps",
  "seemingly",
  "apparently",
  "arguably",
  "presumably",
  "conceivably",
  "likely",
  "unlikely",
  "probable",
  "plausible",
];

export const HEDGE_PHRASES: readonly string[] = [
  "to some extent",
  "in some cases",
  "it is possible that",
  "it seems that",
  "it appears that",
  "we believe that",
  "it is likely that",
  "we feel that",
  "one might argue",
  "it could be argued",
  "there is reason to believe",
];

/**
 * Booster words — overclaiming intensifiers (mirrors the hedge axis).
 * Not in the Python source; added per the engine contract's boosterDensity metric,
 * drawn from the same register the filler list targets (no hype slogans).
 */
export const BOOSTER_WORDS: readonly string[] = [
  "clearly",
  "obviously",
  "undoubtedly",
  "certainly",
  "definitely",
  "surely",
  "evidently",
  "undeniably",
  "unquestionably",
  "indisputably",
  "absolutely",
  "always",
  "never",
  "completely",
  "totally",
  "entirely",
  "extremely",
  "highly",
  "vastly",
  "significantly",
];

/** Weak sentence openers (prefix match on the lowercased, trimmed sentence). */
export const WEAK_OPENERS: readonly string[] = [
  "it is",
  "it was",
  "there is",
  "there are",
  "there was",
  "there were",
  "it has been",
  "it should be noted",
  "it is important",
  "it is worth",
  "it is interesting",
  "it can be seen",
  "as we all know",
  "as is well known",
];

/** Expletive / be-verb openers, used by the weak-opener detector. */
export const ML_JARGON: readonly string[] = [
  "transformer",
  "attention",
  "self-attention",
  "cross-attention",
  "encoder",
  "decoder",
  "embedding",
  "tokenizer",
  "softmax",
  "backpropagation",
  "gradient descent",
  "stochastic gradient descent",
  "batch normalization",
  "layer normalization",
  "dropout",
  "convolution",
  "pooling",
  "recurrent",
  "lstm",
  "gru",
  "generative",
  "discriminative",
  "adversarial",
  "contrastive",
  "variational",
  "autoencoder",
  "diffusion",
  "latent",
  "fine-tuning",
  "pre-training",
  "transfer learning",
  "regularization",
  "overfitting",
  "underfitting",
  "hyperparameter",
  "epoch",
  "batch size",
  "learning rate",
  "loss function",
  "objective function",
  "optimization",
  "inference",
  "training",
  "evaluation",
  "equivariant",
  "invariant",
  "disentangled",
  "causal",
  "counterfactual",
  "interventional",
];

/**
 * Irregular past participles for the passive heuristic.
 * Ported verbatim from PASSIVE_PATTERN's alternation in writing_verify.py.
 */
export const IRREGULAR_PARTICIPLES: readonly string[] = [
  "written",
  "given",
  "taken",
  "driven",
  "spoken",
  "chosen",
  "known",
  "shown",
  "grown",
  "drawn",
  "thrown",
  "blown",
  "sewn",
  "done",
  "gone",
  "run",
  "seen",
  "eaten",
  "come",
  "become",
  "gotten",
  "set",
  "put",
  "cut",
  "hit",
  "let",
  "built",
  "sent",
  "spent",
  "left",
  "lost",
  "found",
  "kept",
  "thought",
  "brought",
  "bought",
  "taught",
  "caught",
  "fought",
  "sought",
  "held",
  "told",
  "sold",
  "read",
  "heard",
  "stood",
  "understood",
  "met",
  "begun",
  "broken",
  "fallen",
  "forgotten",
  "hidden",
  "risen",
  "shaken",
  "stolen",
  "woken",
  "worn",
  "wound",
  "bound",
  "fed",
  "fled",
  "hung",
  "led",
  "lit",
  "paid",
  "said",
  "sat",
  "shot",
  "slid",
  "slung",
  "spun",
  "stung",
  "struck",
  "stuck",
  "swum",
  "swung",
  "torn",
  "woven",
];

/** Be-verbs that head a passive construction. */
export const BE_VERBS: readonly string[] = ["is", "are", "was", "were", "be", "been", "being"];

/**
 * Adverb stoplist: tokens ending in "-ly" that are NOT adverbs (or are common
 * false positives we never want to flag). Lowercased.
 */
export const ADVERB_STOPLIST: ReadonlySet<string> = new Set([
  "only",
  "family",
  "apply",
  "reply",
  "supply",
  "early",
  "likely",
  "italy",
  "holy",
  "ally",
  "rally",
  "fully",
  "duly",
  "imply",
  "comply",
  "multiply",
  "anomaly",
  "assembly",
  "monopoly",
  "panoply",
  "wholly",
  "ugly",
  "jelly",
  "belly",
  "folly",
  "bully",
  "dolly",
  "rely",
  "july",
  "lily",
  "lonely",
  "friendly",
  "unlikely",
]);
